FROM python:3.13.3-alpine AS builder

# Install build dependencies
RUN apk add --no-cache \
    gcc \
    musl-dev \
    libffi-dev \
    libxml2-dev \
    libxslt-dev \
    python3-dev \
    cargo \
    openssl-dev \
    git

WORKDIR /app

# Install poetry
RUN pip3 install poetry

# Copy dependency files
COPY poetry.lock pyproject.toml /app/

# Create minimal structure to make Poetry happy
RUN mkdir /app/kube_web && touch /app/kube_web/__init__.py && touch /app/README.md

# Install dependencies only (no dev dependencies)
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --only main --no-ansi

# Second stage: minimal runtime image
FROM python:3.13.3-alpine

# Install runtime dependencies
RUN apk add --no-cache \
    libxml2 \
    libxslt \
    openssl \
    # Add tzdata for timezone support
    tzdata \
    # Add CA certificates for HTTPS connections
    ca-certificates

WORKDIR /app

# Copy Python packages from builder stage
COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy application code
COPY kube_web /app/kube_web

ARG VERSION=dev

# Replace build version in package and
# add build version to static asset links to break browser cache
RUN sed -i "s/^__version__ = .*/__version__ = \"${VERSION}\"/" /app/kube_web/__init__.py && \
    sed -i "s/v=[0-9A-Za-z._-]*/v=${VERSION}/g" /app/kube_web/templates/base.html

# Create a non-root user to run the application
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# Set Python path to include our application
ENV PYTHONPATH=/app

# Run the application
ENTRYPOINT ["python", "-m", "kube_web"]
